"""
RANANO TensorFlow Hub Super Resolution
---------------------------------------

Purpose:
    Convert the 96x96 image generated by the RANANO DDPM
    into a cleaner 384x384 presentation image.

Pipeline:

    RANANO DDPM
        |
        v
      96x96
        |
        v
    ESRGAN x4
    TensorFlow Hub
        |
        v
     384x384
        |
        v
    Light cleanup
        |
        v
    Final image

Important:
    - The DDPM remains RANANO's trained image generator.
    - ESRGAN is only used for super-resolution.
    - No EDSR.
    - No OpenCV dnn_superres.
    - No image-generation API.
    - Runs on CPU.
    - TensorFlow Hub downloads the ESRGAN model on first use.
    - The downloaded model is cached by TensorFlow Hub afterward.
"""

from __future__ import annotations

import os

# ---------------------------------------------------------------------------
# TensorFlow CPU configuration
# ---------------------------------------------------------------------------
#
# Keep TensorFlow from creating a huge number of CPU threads on Windows.
# This is especially important because RANANO already uses PyTorch for DDPM.
#
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
os.environ.setdefault("TF_NUM_INTRAOP_THREADS", "2")
os.environ.setdefault("TF_NUM_INTEROP_THREADS", "2")

from pathlib import Path

import cv2
import numpy as np
from PIL import Image, ImageEnhance


# ============================================================================
# CONFIGURATION
# ============================================================================

INPUT_SIZE = 96
SCALE = 4
OUTPUT_SIZE = INPUT_SIZE * SCALE

# TensorFlow Hub ESRGAN model.
#
# This is the ESRGAN model used by the TensorFlow Hub image-enhancement
# example.
ESRGAN_MODEL_URL = (
    "https://tfhub.dev/captain-pool/esrgan-tf2/1"
)


# ============================================================================
# MODEL CACHE
# ============================================================================

_sr_model = None
_sr_checked = False


# ============================================================================
# UTILITIES
# ============================================================================

def pil_to_numpy(image: Image.Image) -> np.ndarray:
    """
    Convert PIL image to uint8 RGB NumPy array.
    """

    if image is None:
        raise ValueError("No image was provided.")

    return np.asarray(
        image.convert("RGB"),
        dtype=np.uint8,
    )


def numpy_to_pil(image: np.ndarray) -> Image.Image:
    """
    Convert NumPy image to PIL RGB.
    """

    image = np.clip(
        image,
        0,
        255,
    ).astype(np.uint8)

    return Image.fromarray(
        image,
        mode="RGB",
    )


# ============================================================================
# LOAD ESRGAN
# ============================================================================

def load_model():
    """
    Load TensorFlow Hub ESRGAN once.

    The model is cached in memory after the first successful load.
    """

    global _sr_model
    global _sr_checked

    if _sr_checked:
        return _sr_model

    _sr_checked = True

    try:

        print(
            "[SR] Loading TensorFlow Hub ESRGAN x4...",
            flush=True,
        )

        import tensorflow as tf
        import tensorflow_hub as hub

        # Explicit CPU execution.
        try:
            tf.config.set_visible_devices([], "GPU")
        except Exception:
            # If TensorFlow has already initialized its devices,
            # this may fail. That is harmless because the project
            # intentionally installs tensorflow-cpu.
            pass

        # Keep TensorFlow CPU usage controlled.
        try:
            tf.config.threading.set_intra_op_parallelism_threads(2)
            tf.config.threading.set_inter_op_parallelism_threads(2)
        except Exception:
            pass

        _sr_model = hub.load(
            ESRGAN_MODEL_URL
        )

        print(
            "[SR] TensorFlow Hub ESRGAN x4 ready.",
            flush=True,
        )

        return _sr_model

    except Exception as exc:

        print(
            "[SR] Failed to load TensorFlow Hub ESRGAN:",
            exc,
            flush=True,
        )

        print(
            "[SR] Super-resolution model will be unavailable.",
            flush=True,
        )

        _sr_model = None

        return None


# ============================================================================
# FAST FALLBACK
# ============================================================================

def lanczos_upscale(
    image: Image.Image,
) -> Image.Image:
    """
    CPU fallback.

    This is only used if TensorFlow Hub ESRGAN cannot be loaded.
    """

    print(
        "[SR] Using Lanczos fallback.",
        flush=True,
    )

    rgb = pil_to_numpy(image)

    result = cv2.resize(
        rgb,
        (
            OUTPUT_SIZE,
            OUTPUT_SIZE,
        ),
        interpolation=cv2.INTER_LANCZOS4,
    )

    return numpy_to_pil(result)


# ============================================================================
# ESRGAN SUPER RESOLUTION
# ============================================================================

def super_resolve(
    image: Image.Image,
) -> Image.Image:
    """
    Perform ESRGAN x4 super-resolution.

    96x96 -> 384x384
    """

    if image is None:
        raise ValueError(
            "No image was provided."
        )

    image = image.convert("RGB")

    model = load_model()

    if model is None:
        return lanczos_upscale(image)

    try:

        import tensorflow as tf

        print(
            "[SR] Starting ESRGAN x4 inference...",
            flush=True,
        )

        # ------------------------------------------------------------------
        # Convert PIL -> TensorFlow tensor.
        #
        # ESRGAN expects:
        #
        # [batch, height, width, channels]
        #
        # with float values in approximately [0, 1].
        # ------------------------------------------------------------------

        rgb = pil_to_numpy(image)

        tensor = tf.convert_to_tensor(
            rgb,
            dtype=tf.float32,
        )

        tensor = tensor / 255.0

        tensor = tf.expand_dims(
            tensor,
            axis=0,
        )

        # ------------------------------------------------------------------
        # ESRGAN inference.
        # ------------------------------------------------------------------

        output = model(
            tensor
        )

        # TensorFlow Hub normally returns a tensor directly.
        #
        # Some SavedModel wrappers can return a dictionary. Handle both.
        if isinstance(output, dict):

            if "output" in output:
                output = output["output"]

            else:
                output = next(
                    iter(output.values())
                )

        output = output[0]

        # ------------------------------------------------------------------
        # Convert TensorFlow tensor -> NumPy.
        # ------------------------------------------------------------------

        output = output.numpy()

        output = np.clip(
            output,
            0.0,
            1.0,
        )

        output = (
            output * 255.0
        ).astype(np.uint8)

        result = numpy_to_pil(
            output
        )

        # ------------------------------------------------------------------
        # Guarantee exact output size.
        # ------------------------------------------------------------------

        if result.size != (
            OUTPUT_SIZE,
            OUTPUT_SIZE,
        ):

            result = result.resize(
                (
                    OUTPUT_SIZE,
                    OUTPUT_SIZE,
                ),
                Image.Resampling.LANCZOS,
            )

        print(
            "[SR] ESRGAN complete: "
            f"{image.size[0]}x{image.size[1]} -> "
            f"{result.size[0]}x{result.size[1]}",
            flush=True,
        )

        return result

    except Exception as exc:

        print(
            "[SR] ESRGAN inference failed:",
            exc,
            flush=True,
        )

        return lanczos_upscale(
            image
        )


# ============================================================================
# LIGHT CLEANUP
# ============================================================================

def cleanup(
    image: Image.Image,
) -> Image.Image:
    """
    Very light cleanup after ESRGAN.

    The cleanup is intentionally conservative so that we do not
    over-process the DDPM output.
    """

    rgb = pil_to_numpy(
        image
    )

    # ------------------------------------------------------------------
    # Mild denoising.
    # ------------------------------------------------------------------

    bgr = cv2.cvtColor(
        rgb,
        cv2.COLOR_RGB2BGR,
    )

    denoised = cv2.fastNlMeansDenoisingColored(
        bgr,
        None,
        1,
        1,
        7,
        21,
    )

    rgb = cv2.cvtColor(
        denoised,
        cv2.COLOR_BGR2RGB,
    )

    # ------------------------------------------------------------------
    # Gentle sharpening.
    # ------------------------------------------------------------------

    blurred = cv2.GaussianBlur(
        rgb,
        (0, 0),
        sigmaX=0.8,
    )

    sharpened = cv2.addWeighted(
        rgb,
        1.10,
        blurred,
        -0.10,
        0,
    )

    result = numpy_to_pil(
        sharpened
    )

    # ------------------------------------------------------------------
    # Very mild contrast.
    # ------------------------------------------------------------------

    result = ImageEnhance.Contrast(
        result
    ).enhance(
        1.015
    )

    # ------------------------------------------------------------------
    # Very mild color correction.
    # ------------------------------------------------------------------

    result = ImageEnhance.Color(
        result
    ).enhance(
        1.005
    )

    return result


# ============================================================================
# PUBLIC API
# ============================================================================

def enhance_generated_image(
    image: Image.Image,
) -> Image.Image:
    """
    Main function used by RANANO image generation.

    Pipeline:

        96x96
          |
          v
        ESRGAN x4
          |
          v
        384x384
          |
          v
        Light cleanup
          |
          v
        Final image
    """

    if image is None:
        raise ValueError(
            "No generated image was provided."
        )

    image = image.convert(
        "RGB"
    )

    print(
        "[RANANO] Starting super-resolution...",
        flush=True,
    )

    # Step 1:
    # ESRGAN x4.
    image = super_resolve(
        image
    )

    # Step 2:
    # Gentle cleanup.
    image = cleanup(
        image
    )

    # Step 3:
    # Guarantee final size.
    if image.size != (
        OUTPUT_SIZE,
        OUTPUT_SIZE,
    ):

        image = image.resize(
            (
                OUTPUT_SIZE,
                OUTPUT_SIZE,
            ),
            Image.Resampling.LANCZOS,
        )

    print(
        "[RANANO] Super-resolution complete.",
        flush=True,
    )

    return image


# ============================================================================
# UPLOADED IMAGE API
# ============================================================================

def enhance_uploaded_image(
    image: Image.Image,
) -> Image.Image:
    """
    Enhance an uploaded image.

    The uploaded image is resized to approximately 4x its original
    dimensions while preserving its aspect ratio.

    This is separate from the DDPM generation pipeline.
    """

    if image is None:
        raise ValueError(
            "No uploaded image was provided."
        )

    image = image.convert(
        "RGB"
    )

    original_width, original_height = image.size

    # For uploaded images we still use ESRGAN.
    #
    # The model performs best when given a reasonable input size.
    # Avoid unnecessarily enormous CPU workloads.
    max_input = 512

    scale_down = min(
        1.0,
        max_input / max(
            original_width,
            original_height,
        ),
    )

    if scale_down < 1.0:

        working_width = max(
            1,
            int(original_width * scale_down),
        )

        working_height = max(
            1,
            int(original_height * scale_down),
        )

        image = image.resize(
            (
                working_width,
                working_height,
            ),
            Image.Resampling.LANCZOS,
        )

    enhanced = super_resolve(
        image
    )

    enhanced = cleanup(
        enhanced
    )

    # Preserve the original aspect ratio.
    target_width = max(
        1,
        int(image.size[0] * SCALE),
    )

    target_height = max(
        1,
        int(image.size[1] * SCALE),
    )

    if enhanced.size != (
        target_width,
        target_height,
    ):

        enhanced = enhanced.resize(
            (
                target_width,
                target_height,
            ),
            Image.Resampling.LANCZOS,
        )

    return enhanced


# ============================================================================
# MODEL STATUS
# ============================================================================

def model_name() -> str:
    """
    Return the configured super-resolution model name.
    """

    return "TensorFlow Hub ESRGAN x4"


# ============================================================================
# TEST
# ============================================================================

if __name__ == "__main__":

    import sys

    if len(sys.argv) < 2:

        print(
            "Usage:"
        )

        print(
            "python modules/super_resolution.py input.png"
        )

        raise SystemExit(0)

    input_path = Path(
        sys.argv[1]
    )

    if not input_path.exists():

        print(
            f"File not found: {input_path}"
        )

        raise SystemExit(1)

    print(
        f"[SR] Reading: {input_path}"
    )

    input_image = Image.open(
        input_path
    ).convert("RGB")

    print(
        f"[SR] Input size: {input_image.size}"
    )

    output_image = enhance_generated_image(
        input_image
    )

    output_path = (
        input_path.parent
        / f"{input_path.stem}_esrgan.png"
    )

    output_image.save(
        output_path
    )

    print(
        f"[SR] Output: {output_path}"
    )

    print(
        f"[SR] Output size: {output_image.size}"
    )