"""
RANANO Backend API
------------------

FastAPI backend for RANANO AI Creative Studio.

Core architecture:

    User prompt
        |
        v
    RANANO trained DDPM
        |
        v
      96x96
        |
        v
    TensorFlow Hub ESRGAN x4
        |
        v
      384x384
        |
        v
    Final PNG

IMPORTANT:
- The core fruit image is generated by RANANO's own trained DDPM.
- ESRGAN is ONLY a super-resolution/post-processing stage.
- EDSR has been completely removed from the generation pipeline.
- Optional background generation uses Pollinations.ai and is explicitly
  disclosed in the result note.
"""

import os

# ---------------------------------------------------------------------------
# IMPORTANT WINDOWS / PYTORCH THREAD SETTINGS
# ---------------------------------------------------------------------------
#
# These must be set before importing torch indirectly through modules.
#
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")

import sys
import uuid
import threading

from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Load backend/.env explicitly
# ---------------------------------------------------------------------------

load_dotenv(
    dotenv_path=Path(__file__).resolve().parent / ".env"
)

# ---------------------------------------------------------------------------
# FastAPI
# ---------------------------------------------------------------------------

from fastapi import (
    FastAPI,
    UploadFile,
    File,
    Form,
    HTTPException,
)

from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from pydantic import BaseModel
from PIL import Image


# ---------------------------------------------------------------------------
# Project imports
# ---------------------------------------------------------------------------

PROJECT_ROOT = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

if PROJECT_ROOT not in sys.path:
    sys.path.insert(
        0,
        PROJECT_ROOT,
    )

from modules import (
    image_generation,
    image_enhancement,
    super_resolution,
    video_generation,
    animated_text,
    voice_assistant,
    photo_label,
)


# ===========================================================================
# DIRECTORIES
# ===========================================================================

OUTPUTS_DIR = os.path.join(
    PROJECT_ROOT,
    "outputs",
)

UPLOADS_DIR = os.path.join(
    PROJECT_ROOT,
    "uploads",
)

os.makedirs(
    OUTPUTS_DIR,
    exist_ok=True,
)

os.makedirs(
    UPLOADS_DIR,
    exist_ok=True,
)


# ===========================================================================
# FASTAPI APPLICATION
# ===========================================================================

app = FastAPI(
    title="RANANO API",
    version="2.0",
)


# ===========================================================================
# CORS
# ===========================================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ===========================================================================
# STATIC FILES
# ===========================================================================

app.mount(
    "/files",
    StaticFiles(
        directory=OUTPUTS_DIR
    ),
    name="files",
)


# ===========================================================================
# STARTUP
# ===========================================================================

@app.on_event("startup")
def warm_up_diffusion_model():
    """
    Load the trained DDPM once at startup.

    This avoids loading PyTorch lazily inside the generation worker.
    """

    try:

        print(
            "[startup] Warming up diffusion model...",
            flush=True,
        )

        image_generation.load_model()

        print(
            "[startup] Diffusion model ready.",
            flush=True,
        )

    except FileNotFoundError as exc:

        print(
            "[startup] Diffusion checkpoint not found.",
            flush=True,
        )

        print(
            f"[startup] {exc}",
            flush=True,
        )


# ===========================================================================
# SINGLE GENERATION WORKER
# ===========================================================================

_generation_executor = ThreadPoolExecutor(
    max_workers=1
)


# ===========================================================================
# JOB TRACKER
# ===========================================================================

_jobs = {}

_jobs_lock = threading.Lock()


def _make_job():
    """
    Create a new generation job.

    Progress is represented as 0-100 so the frontend does not need to know
    the internal DDPM/ESRGAN stages.
    """

    job_id = uuid.uuid4().hex

    with _jobs_lock:

        _jobs[job_id] = {
            "status": "running",
            "step": 0,
            "total": 100,
            "stage": "starting",
            "result": None,
            "error": None,
        }

    return job_id


def _update_job(
    job_id,
    step=None,
    stage=None,
):
    """
    Update generation progress.
    """

    with _jobs_lock:

        job = _jobs.get(job_id)

        if job is None:
            return

        if step is not None:

            job["step"] = max(
                0,
                min(
                    100,
                    int(step),
                ),
            )

        if stage is not None:

            job["stage"] = stage


def _finish_job(
    job_id,
    result=None,
    error=None,
):
    """
    Finish a generation job.
    """

    with _jobs_lock:

        job = _jobs.get(job_id)

        if job is None:
            return

        if error:

            job["status"] = "error"
            job["error"] = error
            job["stage"] = "error"

        else:

            job["status"] = "done"
            job["step"] = 100
            job["stage"] = "complete"
            job["result"] = result
            job["error"] = None


@app.get(
    "/api/generation-progress/{job_id}"
)
def generation_progress(
    job_id: str,
):
    """
    Return the current state of a generation job.
    """

    with _jobs_lock:

        job = _jobs.get(job_id)

    if job is None:

        raise HTTPException(
            status_code=404,
            detail="Unknown job_id",
        )

    return job


# ===========================================================================
# FILE SAVING
# ===========================================================================

def _save_and_url(
    pil_image: Image.Image,
    prefix: str,
    ext: str = "png",
) -> str:
    """
    Save a PIL image into outputs/ and return the frontend URL.
    """

    filename = (
        f"{prefix}_"
        f"{uuid.uuid4().hex[:8]}."
        f"{ext}"
    )

    path = os.path.join(
        OUTPUTS_DIR,
        filename,
    )

    pil_image.convert(
        "RGB"
    ).save(
        path,
        format="PNG",
    )

    return (
        f"/files/{filename}"
    )


# ===========================================================================
# HEALTH CHECK
# ===========================================================================

@app.get("/api/health")
def health():
    return {
        "status": "ok",
        "super_resolution": (
            "TensorFlow Hub ESRGAN x4"
        ),
        "generator": (
            "RANANO trained DDPM"
        ),
    }


# ===========================================================================
# RANDOM IMAGE GENERATION
# ===========================================================================

@app.post(
    "/api/generate-image/start"
)
def generate_image_start():

    job_id = _make_job()

    def run():

        try:

            # --------------------------------------------------------------
            # DDPM: 0 -> 80
            # --------------------------------------------------------------

            _update_job(
                job_id,
                1,
                "generating with RANANO DDPM",
            )

            def progress_cb(
                step,
                total,
            ):

                if total:

                    ddpm_progress = (
                        float(step)
                        / float(total)
                    )

                    overall = int(
                        ddpm_progress * 80
                    )

                else:

                    overall = 1

                _update_job(
                    job_id,
                    overall,
                    "generating with RANANO DDPM",
                )

            img = image_generation.generate_image(
                progress_callback=progress_cb
            )

            print(
                "[RANANO] DDPM generation complete: "
                f"{img.size[0]}x{img.size[1]}",
                flush=True,
            )

            # --------------------------------------------------------------
            # ESRGAN: 80 -> 97
            # --------------------------------------------------------------

            _update_job(
                job_id,
                82,
                "enhancing with ESRGAN",
            )

            img = super_resolution.enhance_generated_image(
                img
            )

            _update_job(
                job_id,
                97,
                "saving final image",
            )

            print(
                "[RANANO] ESRGAN enhancement complete: "
                f"{img.size[0]}x{img.size[1]}",
                flush=True,
            )

            # --------------------------------------------------------------
            # SAVE: 97 -> 100
            # --------------------------------------------------------------

            url = _save_and_url(
                img,
                "generated",
            )

            print(
                f"[RANANO] Generation complete: {url}",
                flush=True,
            )

            _finish_job(
                job_id,
                result={
                    "image_url": url,
                    "generation_size": [
                        96,
                        96,
                    ],
                    "final_size": list(
                        img.size
                    ),
                    "enhancement": (
                        "TensorFlow Hub ESRGAN x4"
                    ),
                    "super_resolution_model": (
                        "ESRGAN x4"
                    ),
                },
            )

        except Exception as exc:

            print(
                "[RANANO] Random generation failed:",
                repr(exc),
                flush=True,
            )

            _finish_job(
                job_id,
                error=str(exc),
            )

    _generation_executor.submit(
        run
    )

    return {
        "job_id": job_id
    }


# ===========================================================================
# TEXT TO IMAGE
# ===========================================================================

class TextToImageRequest(
    BaseModel
):

    prompt: str
    use_background: bool = False


@app.post(
    "/api/generate-image-from-text/start"
)
def generate_image_from_text_start(
    req: TextToImageRequest,
):

    job_id = _make_job()

    def run():

        try:

            # --------------------------------------------------------------
            # DDPM PROGRESS
            # --------------------------------------------------------------

            def progress_cb(
                step,
                total,
            ):

                if total:

                    ddpm_progress = (
                        float(step)
                        / float(total)
                    )

                    overall = int(
                        ddpm_progress * 80
                    )

                else:

                    overall = 1

                _update_job(
                    job_id,
                    overall,
                    "generating with RANANO DDPM",
                )

            # --------------------------------------------------------------
            # RANANO DDPM
            # --------------------------------------------------------------

            img, matched_classes, note = (
                image_generation.generate_image_from_prompt(
                    req.prompt,
                    image_generation.CHECKPOINT_PATH,
                    req.use_background,
                    progress_callback=progress_cb,
                )
            )

            print(
                "[RANANO] DDPM generation complete: "
                f"{img.size[0]}x{img.size[1]}",
                flush=True,
            )

            # --------------------------------------------------------------
            # BACKGROUND / COMPOSITING
            # --------------------------------------------------------------

            _update_job(
                job_id,
                84,
                "processing background and composition",
            )

            # The background work, if requested, has already been performed
            # inside generate_image_from_prompt().
            #
            # We keep this separate progress stage so the frontend does not
            # display 100% while post-processing is still running.

            # --------------------------------------------------------------
            # ESRGAN
            # --------------------------------------------------------------

            _update_job(
                job_id,
                88,
                "enhancing with ESRGAN",
            )

            img = super_resolution.enhance_generated_image(
                img
            )

            print(
                "[RANANO] ESRGAN enhancement complete: "
                f"{img.size[0]}x{img.size[1]}",
                flush=True,
            )

            # --------------------------------------------------------------
            # SAVE
            # --------------------------------------------------------------

            _update_job(
                job_id,
                97,
                "saving final image",
            )

            url = _save_and_url(
                img,
                "generated",
            )

            print(
                f"[RANANO] Generation complete: {url}",
                flush=True,
            )

            _finish_job(
                job_id,
                result={
                    "image_url": url,
                    "matched_classes": (
                        matched_classes
                    ),
                    "note": note,
                    "generation_size": [
                        96,
                        96,
                    ],
                    "final_size": list(
                        img.size
                    ),
                    "enhancement": (
                        "TensorFlow Hub ESRGAN x4"
                    ),
                    "super_resolution_model": (
                        "ESRGAN x4"
                    ),
                },
            )

        except Exception as exc:

            print(
                "[RANANO] Text generation failed:",
                repr(exc),
                flush=True,
            )

            _finish_job(
                job_id,
                error=str(exc),
            )

    _generation_executor.submit(
        run
    )

    return {
        "job_id": job_id
    }


# ===========================================================================
# PHOTO LABEL
# ===========================================================================

@app.post(
    "/api/label-photo"
)
async def label_photo_endpoint(
    file: UploadFile = File(...),
    effect: str = Form("fade"),
):

    try:

        contents = await file.read()

        safe_filename = (
            f"{uuid.uuid4().hex[:8]}_"
            f"{file.filename}"
        )

        upload_path = os.path.join(
            UPLOADS_DIR,
            safe_filename,
        )

        with open(
            upload_path,
            "wb",
        ) as f:

            f.write(contents)

        image = Image.open(
            upload_path
        ).convert(
            "RGB"
        )

        gif_filename = (
            f"label_"
            f"{uuid.uuid4().hex[:8]}"
            f".gif"
        )

        gif_path = os.path.join(
            OUTPUTS_DIR,
            gif_filename,
        )

        label, confidence, saved_path = (
            photo_label.label_and_animate(
                image,
                output_path=gif_path,
                effect=effect,
            )
        )

        return {
            "label": label,
            "confidence": confidence,
            "gif_url": (
                f"/files/{gif_filename}"
            ),
        }

    except FileNotFoundError as exc:

        raise HTTPException(
            status_code=503,
            detail=str(exc),
        )


# ===========================================================================
# IMAGE ENHANCEMENT
# ===========================================================================

@app.post(
    "/api/enhance-image"
)
async def enhance_image(
    file: UploadFile = File(...),
    mode: str = Form("fast"),
):

    try:

        contents = await file.read()

        safe_filename = (
            f"{uuid.uuid4().hex[:8]}_"
            f"{file.filename}"
        )

        upload_path = os.path.join(
            UPLOADS_DIR,
            safe_filename,
        )

        with open(
            upload_path,
            "wb",
        ) as f:

            f.write(contents)

        image = Image.open(
            upload_path
        ).convert(
            "RGB"
        )

        # --------------------------------------------------------------
        # Enhancement modes:
        #
        # fast
        #     Classical OpenCV cleanup.
        #
        # quality / esrgan
        #     TensorFlow Hub ESRGAN x4.
        # --------------------------------------------------------------

        if mode.lower() in {
            "quality",
            "esrgan",
            "super_resolution",
        }:

            enhanced = (
                super_resolution.enhance_uploaded_image(
                    image
                )
            )

        else:

            enhanced = (
                image_enhancement.enhance(
                    image,
                    mode="fast",
                )
            )

        url = _save_and_url(
            enhanced,
            "enhanced",
        )

        return {
            "image_url": url,
            "mode": mode,
            "enhancement": (
                "TensorFlow Hub ESRGAN x4"
                if mode.lower()
                in {
                    "quality",
                    "esrgan",
                    "super_resolution",
                }
                else "Fast OpenCV enhancement"
            ),
        }

    except Exception as exc:

        print(
            "[RANANO] Image enhancement failed:",
            repr(exc),
            flush=True,
        )

        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )


# ===========================================================================
# VIDEO GENERATION
# ===========================================================================

class VideoRequest(
    BaseModel
):

    image_urls: list[str]


@app.post(
    "/api/generate-video"
)
def generate_video(
    req: VideoRequest,
):

    images = []

    for url in req.image_urls:

        filename = (
            url.split(
                "/files/"
            )[-1]
        )

        path = os.path.join(
            OUTPUTS_DIR,
            filename,
        )

        if not os.path.exists(path):

            raise HTTPException(
                status_code=404,
                detail=(
                    f"Image not found: {url}"
                ),
            )

        images.append(
            Image.open(
                path
            ).convert(
                "RGB"
            )
        )

    video_filename = (
        f"video_"
        f"{uuid.uuid4().hex[:8]}"
        f".mp4"
    )

    video_path = os.path.join(
        OUTPUTS_DIR,
        video_filename,
    )

    video_generation.generate_video(
        images,
        mode="slideshow",
        output_path=video_path,
    )

    return {
        "video_url": (
            f"/files/{video_filename}"
        )
    }


# ===========================================================================
# ANIMATED TEXT
# ===========================================================================

class AnimateTextRequest(
    BaseModel
):

    text: str
    effect: str = "fade"


@app.post(
    "/api/animate-text"
)
def animate_text(
    req: AnimateTextRequest,
):

    gif_filename = (
        f"text_"
        f"{uuid.uuid4().hex[:8]}"
        f".gif"
    )

    gif_path = os.path.join(
        OUTPUTS_DIR,
        gif_filename,
    )

    animated_text.generate_animated_text(
        req.text,
        output_path=gif_path,
        effect=req.effect,
    )

    return {
        "gif_url": (
            f"/files/{gif_filename}"
        )
    }


# ===========================================================================
# VOICE ASSISTANT / INTENT
# ===========================================================================

class CommandRequest(
    BaseModel
):

    command: str


@app.post(
    "/api/classify-intent"
)
def classify_intent(
    req: CommandRequest,
):

    try:

        result = (
            voice_assistant.handle_command(
                req.command
            )
        )

        return result

    except FileNotFoundError as exc:

        raise HTTPException(
            status_code=503,
            detail=str(exc),
        )


# ===========================================================================
# CHAT
# ===========================================================================

class ChatTurn(
    BaseModel
):

    role: str
    content: str


class ChatRequest(
    BaseModel
):

    message: str
    history: list[ChatTurn] = []
    tool: str = "RANANO Studio"


@app.post(
    "/api/chat"
)
def chat(
    req: ChatRequest,
):

    intent_result = {
        "intent": None,
        "confidence": 0.0,
    }

    # --------------------------------------------------------------
    # Intent classifier
    # --------------------------------------------------------------

    try:

        intent_result = (
            voice_assistant.classify_intent(
                req.message
            )
        )

    except Exception as exc:

        print(
            f"[chat] intent classifier unavailable: {exc}",
            flush=True,
        )

    # --------------------------------------------------------------
    # Conversation history
    # --------------------------------------------------------------

    history_dicts = [
        {
            "role": turn.role,
            "content": turn.content,
        }
        for turn in req.history
    ]

    # --------------------------------------------------------------
    # Groq conversational assistant
    # --------------------------------------------------------------

    reply = (
        voice_assistant.chat_with_groq(
            message=req.message,
            history=history_dicts,
            detected_intent=(
                intent_result.get(
                    "intent"
                )
            ),
            tool_context=req.tool,
        )
    )

    return {
        "reply": reply,
        "intent": (
            intent_result.get(
                "intent"
            )
        ),
        "confidence": (
            intent_result.get(
                "confidence",
                0.0,
            )
        ),
    }